### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shadowTW** [codeblitz97/izel#2]
$ next build
  ▲ Next.js 14.2.8

   Creating an optimized production build ...
(node:21380) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:20848) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ✓ Compiled successfully
   Skipping validation of types
   Linting  ..
 ⚠ The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config

./app/api/getSources/[id]/route.ts
11:7  Warning: 'bky' is assigned a value but never used.  @typescript-eslint/no-unused-vars
114:5  Warning: Unexpected console statement.  no-console

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting
 ✓ Collecting page data
   Generating static pages (0/5)  [==  ] ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/search". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
    at o (C:\Users\legen\OneDrive\Desktop\ayoko\.next\server\chunks\718.js:1:25382)
    at c (C:\Users\legen\OneDrive\Desktop\ayoko\.next\server\chunks\718.js:1:36365)
    at x (C:\Users\legen\OneDrive\Desktop\ayoko\.next\server\app\search\page.js:1:3980)
    at nj (C:\Users\legen\OneDrive\Desktop\ayoko\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:46251)
    at nM (C:\Users\legen\OneDrive\Desktop\ayoko\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:47571)
    at nN (C:\Users\legen\OneDrive\Desktop\ayoko\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:64546)
    at nI (C:\Users\legen\OneDrive\Desktop\ayoko\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:47010)
    at nM (C:\Users\legen\OneDrive\Desktop\ayoko\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:47717)
    at nM (C:\Users\legen\OneDrive\Desktop\ayoko\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:61546)
    at nN (C:\Users\legen\OneDrive\Desktop\ayoko\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:64546)

Error occurred prerendering page "/search". Read more: https://nextjs.org/docs/messages/prerender-error

 ✓ Generating static pages (5/5)

> Export encountered errors on following paths:
        /search/page: /search
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sulvii** [comment]
I know this issue, I've been working to improve the search page as much as I can and I hope I can do this by today

**Comment by sulvii** [comment]
Should be fixed by now 🫡
